export const FETCHING_REG = 'FETCHING_REG';
export const FETCHING_REG_SUCCESS = 'FETCHING_REG_SUCCESS';
export const FETCHING_REG_FAILURE = 'FETCHING_REG_FAILURE';

export const FETCHING_LOGIN = 'FETCHING_LOGIN';
export const FETCHING_LOGIN_SUCCESS = 'FETCHING_LOGIN_SUCCESS';
export const FETCHING_LOGIN_FAILURE = 'FETCHING_LOGIN_FAILURE';
