export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const GET_NEW_CITY = 'GET_NEW_CITY';
export const GET_NEW_GEO = 'GET_NEW_GEO';

export const BACK_INIT_TIPBAR = 'BACK_INIT_TIPBAR';
